FROM rhel7:latest
MAINTAINER Luiz Carvalho <lucarval@redhat.com>

ARG REPO_URL
ARG UPDATES

ADD ${REPO_URL} /etc/yum.repos.d/internal.repo
RUN if [ $UPDATES ]; then yum update -y; fi && \
    yum install -y \
      openshift-clients \
      iproute \
      koji-containerbuild-cli \
    && yum clean all

ADD bin/ /usr/local/bin/
ADD configs/ /configs

RUN chmod +x /usr/local/bin/*

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["sleep", "infinity"]
