FROM osbs-box:rhel7

RUN yum install -y \
      atomic-openshift-clients \
      iproute \
      koji-containerbuild-cli \
    && yum clean all

ADD bin/ /usr/local/bin/
ADD configs/ /configs

RUN chmod +x /usr/local/bin/*

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["sleep", "infinity"]
