FROM osbs-box:fedora

RUN dnf -y --refresh install \
      origin-clients \
      iproute \
      koji-containerbuild \
    && dnf clean all

ADD bin/ /usr/local/bin/
ADD configs/ /configs

RUN chmod +x /usr/local/bin/*

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["sleep", "infinity"]
