- name: Prepare for cleanup
  hosts: localhost
  tags:
    - always

  tasks:
    - name: Try to log in as openshift admin
      command: oc login -u system:admin
      register: oc_login
      changed_when: oc_login.rc == 0
      # If login failed, cluster is probably down - that means steps which use
      # `oc` must be skipped, but otherwise, cleanup can proceed as usual
      ignore_errors: true


- name: Delete koji
  hosts: localhost
  gather_facts: false
  tags:
    - koji
    # All tags related to koji PVs (deleting PVs while in use is a bad idea)
    - pvs
    - koji_pvs
    - koji_db_pv
    - koji_files_pv
    # One tag to rule them all
    - everything

  tasks:
    - name: Delete koji namespace from openshift
      command: oc delete namespace "{{ koji_namespace }}"
      register: delete_koji_namespace
      changed_when: delete_koji_namespace.rc == 0
      failed_when: delete_koji_namespace.rc != 0 and
                   'not found' not in delete_koji_namespace.stderr
      when: not oc_login.failed

    - name: Delete koji PVs from openshift
      command: oc delete pv --selector volume=koji-volume
      register: delete_koji_pvs
      changed_when: delete_koji_pvs.rc == 0 and
                    delete_koji_pvs.stdout != 'No resources found'
      failed_when: delete_koji_pvs.rc != 0
      when: not oc_login.failed


- name: Delete docker registry
  hosts: localhost
  gather_facts: false
  tags:
    - registry
    - pvs
    - registry_pv
    - everything

  tasks:
    - name: Delete registry namespace from openshift
      command: oc delete namespace "{{ registry_namespace }}"
      register: delete_registry_namespace
      changed_when: delete_registry_namespace.rc == 0
      failed_when: delete_registry_namespace.rc != 0 and
                   'not found' not in delete_registry_namespace.stderr
      when: not oc_login.failed

    - name: Delete registry PV from openshift
      command: oc delete pv registry-data
      register: delete_registry_pv
      changed_when: delete_registry_pv.rc == 0
      failed_when: delete_registry_pv.rc != 0 and
                   'not found' not in delete_registry_pv.stderr
      when: not oc_login.failed


- name: Delete OSBS orchestrator and worker namespaces
  hosts: localhost
  gather_facts: false
  tags:
    - namespaces
    - everything

  tasks:
    - name: Delete orchestrator and worker namespaces from openshift
      command: oc delete namespace "{{ item }}"
      register: delete_osbs_namespace
      changed_when: delete_osbs_namespace.rc == 0
      failed_when: delete_osbs_namespace.rc != 0 and
                   'not found' not in delete_osbs_namespace.stderr
      loop:
        - "{{ orchestrator_namespace }}"
        - "{{ worker_namespace }}"
      when: not oc_login.failed


- name: Delete persistent volume data
  hosts: localhost
  gather_facts: false
  become: true
  tags:
    - never
    - pvs
    - everything

  tasks:
    - name: Delete koji-db-data PV directory
      file:
        path: "{{ koji_db_data_dir }}"
        state: absent
      tags:
        - koji_pvs
        - koji_db_pv

    - name: Delete koji-files PV directory
      file:
        path: "{{ koji_files_dir }}"
        state: absent
      tags:
        - koji_pvs
        - koji_files_pv

    - name: Delete registry-data PV directory
      file:
        path: "{{ registry_data_dir }}"
        state: absent
      tags:
        - registry_pv


- name: Delete remaining OSBS-Box data
  hosts: localhost
  gather_facts: false
  tags:
    - never
    - everything

  tasks:
    - name: Delete certificate directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ koji_certs_dir }}"
        - "{{ registry_certs_dir }}"
        - "{{ certificates_dir }}"
      tags:
        - certificates

    - name: Delete openshift files directory
      file:
        path: "{{ openshift_files }}"
        state: absent
      tags:
        - openshift_files

    - name: Delete OSBS-Box data directory
      # At this point, it should only contain empty directories (if anything)
      file:
        path: "{{ osbs_box_data_dir }}"
        state: absent
