- name: Generate koji certificates
  hosts: localhost
  vars:
    # This is a constant, please do not override
    koji_certs_basic:
      - kojiadmin
      - kojiosbs
      - kojibuilder
      - kojiweb

  pre_tasks:
    - name: Make sure python-cryptography package is installed
      package:
        name: "python{{ ansible_python.version.major }}-cryptography"
        state: present
      when: allow_pkg_install
      become: true

    - name: Make sure koji certificates directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ koji_certs_work }}"
        - "{{ koji_certs_final }}"

  tasks:
    - name: Generate private keys for all certificates
      openssl_privatekey:
        path: "{{ koji_certs_work }}/{{ item }}.key"
      with_items:
        - koji-ca
        - koji-hub
        - "{{ koji_certs_basic }}"

    - name: Generate CA certificate CSR
      openssl_csr:
        path: "{{ koji_certs_work }}/koji-ca.csr"
        privatekey_path: "{{ koji_certs_work }}/koji-ca.key"
        common_name: koji-ca
        basic_constraints:
          - "CA:TRUE"

    - name: Self-sign CA certificate CSR
      openssl_certificate:
        provider: selfsigned
        selfsigned_not_after: +365d
        path: "{{ koji_certs_final }}/koji-ca.crt"
        csr_path: "{{ koji_certs_work }}/koji-ca.csr"
        privatekey_path: "{{ koji_certs_work }}/koji-ca.key"
        # Generate the certificate even if it already exists,
        # otherwise an expired certificate would not be overwritten
        force: true

    - name: Generate koji-hub CSR
      openssl_csr:
        path: "{{ koji_certs_work }}/koji-hub.csr"
        privatekey_path: "{{ koji_certs_work }}/koji-hub.key"
        common_name: koji-hub
        subject_alt_name:
          - "DNS:koji-hub"
          - "DNS:koji-hub.{{ koji_namespace }}.svc"
          - "DNS:koji-hub-{{ koji_namespace }}.127.0.0.1.nip.io"

    - name: Generate basic client CSRs
      openssl_csr:
        path: "{{ koji_certs_work }}/{{ item }}.csr"
        privatekey_path: "{{ koji_certs_work }}/{{ item }}.key"
        common_name: "{{ item }}"
      loop:
        "{{ koji_certs_basic }}"

    - name: Sign client CSRs
      openssl_certificate:
        provider: ownca
        ownca_not_after: +365d
        path: "{{ koji_certs_work }}/{{ item }}.crt"
        csr_path: "{{ koji_certs_work }}/{{ item }}.csr"
        ownca_path: "{{ koji_certs_final }}/koji-ca.crt"
        ownca_privatekey_path: "{{ koji_certs_work }}/koji-ca.key"
        # Generate the certificate even if it already exists,
        # otherwise an expired certificate would not be overwritten
        force: true
      with_items:
        - koji-hub
        - "{{ koji_certs_basic }}"

    - name: Append private keys to client certificates, save as .pem files
      assemble:
        dest: "{{ koji_certs_final }}/{{ item }}.pem"
        src: "{{ koji_certs_work }}"
        regexp: "{{ item }}\\.(crt|key)"
      with_items:
        - koji-hub
        - "{{ koji_certs_basic }}"
