- name: Generate koji certificates
  hosts: localhost
  vars:
    # This is a constant, please do not override
    koji_client_certs:
      - kojiadmin
      - kojiosbs
      - kojibuilder
      - kojiweb

  pre_tasks:
    - name: Make sure python-cryptography package is installed
      package:
        name: "python{{ ansible_python.version.major }}-cryptography"
        state: present
      when: allow_pkg_install
      become: true

    - name: Make sure koji certificate directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ koji_certs_work }}"
        - "{{ koji_certs_final }}"

  tasks:
    - name: Check if CA certificate exists and has not expired
      openssl_certificate:
        provider: assertonly
        path: "{{ koji_certs_final }}/koji-ca.crt"
        has_expired: false
      ignore_errors: true
      register: check_ca

    - block:
        - name: Generate CA private key
          openssl_privatekey:
            path: "{{ koji_certs_work }}/koji-ca.key"

        - name: Generate CA CSR
          openssl_csr:
            path: "{{ koji_certs_work }}/koji-ca.csr"
            privatekey_path: "{{ koji_certs_work }}/koji-ca.key"
            common_name: koji-ca
            basic_constraints:
              - "CA:TRUE"

        - name: Self-sign CA CSR
          openssl_certificate:
            provider: selfsigned
            selfsigned_not_after: +365d
            path: "{{ koji_certs_final }}/koji-ca.crt"
            csr_path: "{{ koji_certs_work }}/koji-ca.csr"
            privatekey_path: "{{ koji_certs_work }}/koji-ca.key"
            # Generate the certificate even if it already exists,
            # otherwise an expired certificate would not be overwritten
            force: true
      when: check_ca.failed

    - name: Generate certificates for all koji components
      include_tasks: tasks/generate-ownca-cert.yaml
      vars:
        dir: "{{ koji_certs_final }}"
        cert: "{{ item }}"
        ca:
          crt_path: "{{ koji_certs_final }}/koji-ca.crt"
          key_path: "{{ koji_certs_work }}/koji-ca.key"
        # If CA certificate changed, recreate everything
        force: "{{ check_ca.failed }}"
      loop:
        - name: koji-hub
          subject_alt_name:
            - "DNS:localhost"   # Same pod
            - "DNS:koji-hub"  # Different pod in the same namespace
            - "DNS:koji-hub.{{ koji_namespace }}"   # Pod in different namespace
            - "DNS:koji-hub.{{ osbs_box_host }}"  # External route
        - name: kojiweb
        - name: kojibuilder
        - name: kojiadmin
        - name: kojiosbs

    - name: Combine private keys with certificates, save as .pem files
      assemble:
        dest: "{{ koji_certs_final }}/{{ item }}.pem"
        src: "{{ koji_certs_final }}"
        regexp: "{{ item }}\\.(crt|key)"
      loop:
        "{{ koji_client_certs }}"

    - name: Generate PKCS#12 client certificates for browsers
      openssl_pkcs12:
        path: "{{ koji_certs_final }}/{{ item }}.p12"
        privatekey_path: "{{ koji_certs_final }}/{{ item }}.key"
        certificate_path: "{{ koji_certs_final }}/{{ item }}.crt"
        friendly_name: "{{ item }}"
      loop:
        "{{ koji_client_certs }}"
