- name: Generate all certificates for OSBS-Box
  hosts: localhost

  pre_tasks:
    - name: Make sure python-cryptography package is installed
      package:
        name: "python{{ ansible_python.version.major }}-cryptography"
        state: present
      when: allow_pkg_install
      become: true

    - name: Make sure certificate directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ certificates_dir }}"
        - "{{ koji_certs_dir }}"

  tasks:
    - name: Check if CA certificate exists and has not expired
      openssl_certificate:
        provider: assertonly
        path: "{{ certificates_dir }}/osbs-box-ca.crt"
        has_expired: false
      ignore_errors: true
      register: check_ca

    - block:
        - name: Generate CA private key
          openssl_privatekey:
            path: "{{ certificates_dir }}/osbs-box-ca.key"

        - name: Generate CA CSR
          openssl_csr:
            path: "{{ certificates_dir }}/osbs-box-ca.csr"
            privatekey_path: "{{ certificates_dir }}/osbs-box-ca.key"
            common_name: OSBS-Box
            basic_constraints:
              - "CA:TRUE"

        - name: Self-sign CA CSR
          openssl_certificate:
            provider: selfsigned
            selfsigned_not_after: +365d
            path: "{{ certificates_dir }}/osbs-box-ca.crt"
            csr_path: "{{ certificates_dir }}/osbs-box-ca.csr"
            privatekey_path: "{{ certificates_dir }}/osbs-box-ca.key"
            # Generate the certificate even if it already exists,
            # otherwise an expired certificate would not be overwritten
            force: true
      when: check_ca.failed

    - name: Generate certificates for all koji components
      include_tasks: tasks/generate-ownca-cert.yaml
      vars:
        dir: "{{ koji_certs_dir }}"
        cert: "{{ item }}"
        ca:
          crt_path: "{{ certificates_dir }}/osbs-box-ca.crt"
          key_path: "{{ certificates_dir }}/osbs-box-ca.key"
        # If CA certificate changed, recreate everything
        force: "{{ check_ca.failed }}"
      loop:
        - name: koji-hub
          subject_alt_name:
            - "DNS:localhost"   # Same pod
            - "DNS:koji-hub"  # Different pod in the same namespace
            - "DNS:koji-hub.{{ koji_namespace }}"   # Pod in different namespace
            - "DNS:koji-hub.{{ osbs_box_host }}"  # External route
        - name: kojiweb
        - name: kojibuilder
        - name: kojiadmin
        - name: kojiosbs

    - block:
        - name: Combine private keys with certificates, save as .pem files
          assemble:
            dest: "{{ koji_certs_dir }}/{{ item }}.pem"
            src: "{{ koji_certs_dir }}"
            regexp: "{{ item }}\\.(crt|key)"
          loop:
            "{{ koji_client_certs }}"

        - name: Generate PKCS#12 client certificates for browsers
          openssl_pkcs12:
            path: "{{ koji_certs_dir }}/{{ item }}.p12"
            privatekey_path: "{{ koji_certs_dir }}/{{ item }}.key"
            certificate_path: "{{ koji_certs_dir }}/{{ item }}.crt"
            friendly_name: "{{ item }}"
          loop:
            "{{ koji_client_certs }}"
      vars:
        koji_client_certs:
          - kojiweb
          - kojibuilder
          - kojiadmin
          - kojiosbs
