FROM osbs-box:rhel7

RUN yum install -y \
        mock \
        koji \
        koji-builder \
        koji-containerbuild-builder \
        osbs-client \
        python-osbs-client \
        python-hashlib \
        python-pip \
        findutils \
    && yum clean all

ADD etc/ /etc/
ADD bin/ /usr/local/bin/
RUN chmod +x /usr/local/bin/*

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/sbin/init"]
