FROM osbs-box:rhel7

VOLUME [\
    "/opt/osbs", \
    "/opt/koji-clients", \
    "/etc/pki/koji", \
    "/certs", \
    "/auth"\
]

EXPOSE 80

RUN yum install -y \
        openssl \
        hostname \
        httpd \
        httpd-tools \
    && yum clean all

ADD opt/ /opt/
ADD etc/ /etc/
ADD bin/ /usr/local/bin/
ADD root/ /root/

RUN ls -l /usr/local/bin
RUN /usr/local/bin/setup.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["httpd", "-D", "FOREGROUND"]
