kind: Template
apiVersion: v1
metadata:
  name: cachito-athens
  description: >
    athens for cachito

labels:
  app: cachito-athens

parameters:
  - name: OSBS_BOX_HOST
    description: Hostname of the machine running OSBS-Box
    value: localhost
    required: true

objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: cachito-athens
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        metadata:
          name: cachito-athens
          labels:
            app: cachito-athens
        spec:
          containers:
            - name: cachito-athens
              image: docker.io/gomods/athens:v0.9.0
              ports:
                - containerPort: 3000
              env:
                - name: ATHENS_DISK_STORAGE_ROOT
                  value: "/var/lib/athens"
                - name: ATHENS_STORAGE_TYPE
                  value: "disk"
              volumeMounts:
                - name: cachito-athens-storage
                  mountPath: "/var/lib/athens"
          imagePullSecrets:
            - name: dockerhub
          volumes:
            - name: cachito-athens-storage
              persistentVolumeClaim:
                claimName: cachito-athens-storage

  - kind: Service
    apiVersion: v1
    metadata:
      name: cachito-athens
    spec:
      selector:
        app: cachito-athens
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000

  - kind: Route
    apiVersion: v1
    metadata:
      name: cachito-athens
    spec:
      host: cachito-athens.${OSBS_BOX_HOST}
      to:
        kind: Service
        name: cachito-athens
      port:
        targetPort: "3000"
