kind: Template
apiVersion: v1
metadata:
  name: cachito-worker
  description: >
    cachito-worker

labels:
  app: cachito-worker

parameters:
  - name: OSBS_BOX_REPO
    description: Repository to build the image from
    value: https://github.com/containerbuildsystem/osbs-box
    required: true

  - name: OSBS_BOX_VERSION
    description: Branch/tag/commit within the repository specified above
    value: master
    required: true

  - name: CACHITO_PIP_REF
    description: >
      Pip URL to install cachito from (git+<repo>[@<version>])
    value: git+https://github.com/release-engineering/cachito
    required: true

  - name: OSBS_BOX_HOST
    description: Hostname of the machine running OSBS-Box
    value: localhost
    required: true

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: cachito-worker
    spec: {}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: cachito-worker
    spec:
      source:
        type: Git
        git:
          uri: ${OSBS_BOX_REPO}
          ref: ${OSBS_BOX_VERSION}
        contextDir: cachito-worker
        secrets:
          - secret:
              name: cachito-ca
            destinationDir: etc/ssl/certs
          - secret:
              name: cachito-certs
            destinationDir: etc/pki/cachito
        configMaps:
          - configMap:
              name: cachito-worker-celery
            destinationDir: etc/cachito/
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true
          from:
            kind: DockerImage
            name: registry.fedoraproject.org/fedora:32
          buildArgs:
            - name: CACHITO_PIP_REF
              value: ${CACHITO_PIP_REF}
      output:
        to:
          kind: ImageStreamTag
          name: cachito-worker:latest

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: cachito-worker
    spec:
      replicas: 1
      selector:
        app: cachito-worker
      strategy:
        type: Recreate
      template:
        metadata:
          name: cachito-worker
          labels:
            app: cachito-worker
        spec:
          containers:
            - name: cachito-worker
              image: cachito-worker:latest
              ports:
                - containerPort: 8080
              env:
                - name: REQUESTS_CA_BUNDLE
                  value: /etc/ssl/certs/osbs-box-ca.crt
              volumeMounts:
                - name: cachito-archives
                  mountPath: /var/lib/cachito-archives/bundles
          volumes:
            - name: cachito-archives
              persistentVolumeClaim:
                claimName: cachito-archives
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - cachito-worker
            from:
              kind: ImageStreamTag
              name: cachito-worker:latest

  - kind: Service
    apiVersion: v1
    metadata:
      name: cachito-worker
    spec:
      selector:
        app: cachito-worker
      ports:
        - name: "80"
          port: 80
          targetPort: 8080
