---
#
# Install required prerequisites for Fedora 32 Workstation for OSBS-Box to be successful.
#
- name: Install Tools
  hosts: all

  tasks:
  - name: enable ssh
    service:
      name: sshd
      state: started
      enabled: yes
  - name: install docker
    yum:
      name: docker
      state: latest
  - name: Add insecure-registry
    lineinfile:
      path: /etc/sysconfig/docker
      insertbefore: "^\""
      line: "  --insecure-registry \"172.30.0.0/16\""
    notify: restart docker
  - name: start docker
    service: 
      name: docker
      state: started
      enabled: yes
  - name: install origin-clients
    yum: 
      name: origin-clients
      state: latest
  - name: install python-devel
    yum:
      name: python-devel
      state: latest
  - name: add root to docker
    user:
      name: root
      groups: docker
      append: yes
  # Need a message to reboot at the end. 
  - name: modify cgroup
    replace: 
      path: /boot/efi/EFI/fedora/grubenv
      regexp: '(^kernelopts.+)(?<!systemd\.unified_cgroup_hierarchy\=0)$'
      replace: '\1 systemd.unified_cgroup_hierarchy=0'
    notify: "Restart system"

  # Restart Docker if necessary.
  handlers:
    - name: restart docker
      service: 
        name: docker
        state: restarted
      listen: "restart docker"
    - name: Restart system
      debug:
        msg: "Kernel parameters changed.  Please reboot the host"

