FROM registry.fedoraproject.org/fedora:27
MAINTAINER Luiz Carvalho <lucarval@redhat.com>

ARG UPDATES
ARG UPDATES_TESTING

RUN if [ $UPDATES ]; then dnf update -y; fi && \
    if [ $UPDATES_TESTING ]; then \
            dnf install -y dnf-plugins-core && \
            dnf config-manager --set-enable updates-testing &&\
            dnf -y update; fi
