name: Lint Markdown files

on: [pull_request]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    container:
      image: pipelinecomponents/markdownlint:latest

    steps:
    - uses: actions/checkout@v1

    - name: Lint Markdown files
      # We have to update to latest mdl
      run: gem install mdl; /usr/local/bundle/bin/mdl -g .
